### ISSUE TITLE
Wrong encoding of CI instruction

### ISSUE THREAD

**Issue by pixelspark** [michaelmelanson/riscy#5] opened 2022-12-30 17:18 UTC
While using your code as an (excellent!) reference while implementing my own small rv32 assembler, I stumbled across this apparent small error:

https://github.com/michaelmelanson/riscy/blob/cfab625aeaf8ea402ea877aafd30ae84dfc22df0/isa/src/instruction.rs#LL717C31-L717C31

The CI instruction format does not use the abbreviated (3 bit) register identifiers - it actually uses the regular ones. The call to `encode_prime` should therefore be replaced with a simple `encode`.

**Comment by michaelmelanson** [comment] 2022-12-31 01:05
Thanks for pointing this out, and I'm glad this little project of mine has been useful to you! 

I'm not surprised you found a bug there, honestly — the instruction encoding for the "C" extension is incomplete, as you can tell from all the `todo!`s all around that. I probably should have left that one as a `todo!` too, and I'm not sure why I didn't.

If you'd like to take a shot at fixing it up, issue #3 is about finishing the encoding for that extension, and there's a checkmark about the `CI` instruction format in particular. I'd appreciate a PR about it, if you have the time and interest. I've been working on other projects lately but some day I might come back to this, and it might be useful to other people.

In the meantime, I'm going to close this issue as a duplicate of #3.

**Closed as not planned by michaelmelanson** 2022-12-31 01:05 UTC
